export const ADD_ARTICLES = 'ADD_ARTICLES'
export const ADD_TAGS = 'ADD_TAGS'
export const SELECT_TAG = 'SELECT_TAG'
export const LOGGED_USER = 'LOGGED_USER'
export const ERROR = 'ERROR'
export const AUTH_HEADER = 'AUTH_HEADER'
