export const ADD_ARTICLES = 'ADD_ARTICLES'
export const ADD_TAGS = 'ADD_TAGS'
export const SELECT_TAG = 'SELECT_TAG'
export const LOGGED_USER = 'LOGGED_USER'
export const ERROR = 'ERROR'
export const AUTH_HEADER = 'AUTH_HEADER'
export const IS_LOGGED_IN = 'IS_LOGGED_IN'
export const UPDATE_USER = 'UPDATE_USER'
export const SINGLE_ARTICLE = 'SINGLE_ARTICLE'
export const USER_PROFILE = 'USER_PROFILE'

